import json
import random

# 生成100个示例关键词（实际使用时可以替换为自己的关键词列表）
keywords = ["visualization",
      "task analysis",
      "three-dimensional displays",
      "data visualization",
      "virtual reality",
      "visual analytics",
      "computational modeling",
      "shape",
      "training",
      "augmented reality",
      "solid modeling",
      "rendering (computer graphics)",
      "data models",
      "layout",
      "geometry",
      "deep learning",
      "feature extraction",
      "image reconstruction",
      "image color analysis",
      "semantics",
      "measurement",
      "virtual environments",
      "mixed reality",
      "point cloud compression",
      "analytical models",
      "behavioral sciences",
      "encoding",
      "faces",
      "navigation",
      "predictive models",
      "real-time systems",
      "resists",
      "uncertainty",
      "avatars",
      "bars",
      "machine learning",
      "optimization",
      "pipelines",
      "collaboration",
      "estimation",
      "extended reality",
      "legged locomotion",
      "neural networks",
      "topology",
      "usability",
      "videos",
      "animation",
      "haptic interfaces",
      "taxonomy",
      "cameras",
      "electronic mail",
      "information visualization",
      "redirected walking",
      "trajectory",
      "cybersickness",
      "distortion",
      "force",
      "interviews",
      "lighting",
      "annotations",
      "codes",
      "convolution",
      "data mining",
      "dimensionality reduction",
      "immersive analytics",
      "manifolds",
      "surveys",
      "tracking",
      "volume rendering",
      "adaptation models",
      "biological system modeling",
      "correlation",
      "data",
      "data analysis",
      "decoding",
      "gaze tracking",
      "graph drawing",
      "guidelines",
      "human-computer interaction",
      "image resolution",
      "market research",
      "mathematical models",
      "noise measurement",
      "reflectivity",
      "transformers",
      "user experience",
      "aerospace electronics",
      "clustering algorithms",
      "cognition",
      "deformation",
      "games",
      "generators",
      "graphics processing units",
      "headphones",
      "interaction",
      "keyboards",
      "meteorology",
      "performance evaluation",
      "sports",
      "standards",
      "surface reconstruction"]

# 读取并解析JSON数据
with open("../data/jsondata/txtJsonData_clean.json", "r", encoding="utf-8") as f:
    data = json.load(f)

for entry in data:
    # 随机选择4-5个不重复的关键词
    k = random.randint(3, 6)
    selected_keywords = random.sample(keywords, k)
    entry["keywords"] = selected_keywords


# 输出修改后的JSON（或保存到文件）
with open("../data/jsondata/random_kw.json", "w") as f:
    json.dump(data, f, indent=2)